#!/usr/bin/env python

Import("env")

env.drivers_sources = []

# OS drivers
SConscript("unix/SCsub") # ok
SConscript("windows/SCsub") # ok

# Sounds drivers
SConscript("alsa/SCsub") # ok
SConscript("coreaudio/SCsub") # ok
SConscript("pulseaudio/SCsub") # ok
if env["platform"] == "windows":
    SConscript("wasapi/SCsub") # ok
if env["xaudio2"]:
    SConscript("xaudio2/SCsub")  # a voir flag + link

# Midi drivers
SConscript("alsamidi/SCsub") # ok
SConscript("coremidi/SCsub") # ok
SConscript("winmidi/SCsub") # ok

# Graphics drivers
if env["platform"] != "server" and env["platform"] != "javascript":
    #    SConscript('gles2/SCsub')
    SConscript("vulkan/SCsub") # a voir bordel
    SConscript("gl_context/SCsub") # a voir bordel
else:
    SConscript("dummy/SCsub") # ok

# Core dependencies
SConscript("png/SCsub") # a voir bordel
SConscript("spirv-reflect/SCsub") # a voir bordel

if env["vsproj"]:
    import os

    path = os.getcwd()
    # Change directory so the path resolves correctly in the function call.
    os.chdir("..")
    env.AddToVSProject(env.drivers_sources)
    os.chdir(path)

env.add_source_files(env.drivers_sources, "*.cpp")

lib = env.add_library("drivers", env.drivers_sources)
env.Prepend(LIBS=[lib])
