version: '3.7'

services:

  base:
    build: base
    image: godot/build_base

  linux:
    depends_on:
      - base
    build: linux
    image: godot/build_linux
    volumes:
      - ../../:/build
    env_file:
      - ".env"
    user: ${UID}:${GID}

  windows:
    depends_on:
      - base
    build: windows
    image: godot/build_windows
    volumes:
      - ../../:/build
    env_file:
      - ".env"
    user: ${UID}:${GID}